apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/DexaiRobotics/fullstack
    changes:
    - command:
        name: /bin/bash
        args:
        - .lighthouse/jenkins-x/updatebot.sh
        - catkin_src/robot_msgs
