"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class double_t(object):
    __slots__ = ["utime", "data"]

    __typenames__ = ["int64_t", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.utime = 0
        self.data = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(double_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qd", self.utime, self.data))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != double_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return double_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = double_t()
        self.utime, self.data = struct.unpack(">qd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if double_t in parents: return 0
        tmphash = (0xb3401a10ab361f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if double_t._packed_fingerprint is None:
            double_t._packed_fingerprint = struct.pack(">Q", double_t._get_hash_recursive([]))
        return double_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", double_t._get_packed_fingerprint())[0]

