"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import robot_msgs.bool

class driver_status_t(object):
    __slots__ = ["utime", "driver_running", "err_msg", "robot_mode", "has_plan", "current_plan_utime", "plan_start_utime", "paused", "pause_sources", "brakes_locked", "user_stopped", "compliant_push_active", "torque_enabled"]

    __typenames__ = ["int64_t", "robot_msgs.bool", "string", "int16_t", "robot_msgs.bool", "int64_t", "int64_t", "robot_msgs.bool", "string", "robot_msgs.bool", "robot_msgs.bool", "robot_msgs.bool", "robot_msgs.bool"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.driver_running = robot_msgs.bool()
        self.err_msg = ""
        self.robot_mode = 0
        self.has_plan = robot_msgs.bool()
        self.current_plan_utime = 0
        self.plan_start_utime = 0
        self.paused = robot_msgs.bool()
        self.pause_sources = ""
        self.brakes_locked = robot_msgs.bool()
        self.user_stopped = robot_msgs.bool()
        self.compliant_push_active = robot_msgs.bool()
        self.torque_enabled = robot_msgs.bool()

    def encode(self):
        buf = BytesIO()
        buf.write(driver_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.driver_running._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.driver_running._encode_one(buf)
        __err_msg_encoded = self.err_msg.encode('utf-8')
        buf.write(struct.pack('>I', len(__err_msg_encoded)+1))
        buf.write(__err_msg_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">h", self.robot_mode))
        assert self.has_plan._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.has_plan._encode_one(buf)
        buf.write(struct.pack(">qq", self.current_plan_utime, self.plan_start_utime))
        assert self.paused._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.paused._encode_one(buf)
        __pause_sources_encoded = self.pause_sources.encode('utf-8')
        buf.write(struct.pack('>I', len(__pause_sources_encoded)+1))
        buf.write(__pause_sources_encoded)
        buf.write(b"\0")
        assert self.brakes_locked._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.brakes_locked._encode_one(buf)
        assert self.user_stopped._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.user_stopped._encode_one(buf)
        assert self.compliant_push_active._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.compliant_push_active._encode_one(buf)
        assert self.torque_enabled._get_packed_fingerprint() == robot_msgs.bool._get_packed_fingerprint()
        self.torque_enabled._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != driver_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return driver_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = driver_status_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.driver_running = robot_msgs.bool._decode_one(buf)
        __err_msg_len = struct.unpack('>I', buf.read(4))[0]
        self.err_msg = buf.read(__err_msg_len)[:-1].decode('utf-8', 'replace')
        self.robot_mode = struct.unpack(">h", buf.read(2))[0]
        self.has_plan = robot_msgs.bool._decode_one(buf)
        self.current_plan_utime, self.plan_start_utime = struct.unpack(">qq", buf.read(16))
        self.paused = robot_msgs.bool._decode_one(buf)
        __pause_sources_len = struct.unpack('>I', buf.read(4))[0]
        self.pause_sources = buf.read(__pause_sources_len)[:-1].decode('utf-8', 'replace')
        self.brakes_locked = robot_msgs.bool._decode_one(buf)
        self.user_stopped = robot_msgs.bool._decode_one(buf)
        self.compliant_push_active = robot_msgs.bool._decode_one(buf)
        self.torque_enabled = robot_msgs.bool._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if driver_status_t in parents: return 0
        newparents = parents + [driver_status_t]
        tmphash = (0x1b4812cb45c45e9e+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)+ robot_msgs.bool._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if driver_status_t._packed_fingerprint is None:
            driver_status_t._packed_fingerprint = struct.pack(">Q", driver_status_t._get_hash_recursive([]))
        return driver_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", driver_status_t._get_packed_fingerprint())[0]

