"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joint_pos_cmd_t(object):
    __slots__ = ["utime", "num_joints", "num_confs", "wait_for_ack", "cmd_joint_positions"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "boolean", "double"]

    __dimensions__ = [None, None, None, None, ["num_confs", "num_joints"]]

    def __init__(self):
        self.utime = 0
        self.num_joints = 0
        self.num_confs = 0
        self.wait_for_ack = False
        self.cmd_joint_positions = []

    def encode(self):
        buf = BytesIO()
        buf.write(joint_pos_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiib", self.utime, self.num_joints, self.num_confs, self.wait_for_ack))
        for i0 in range(self.num_confs):
            buf.write(struct.pack('>%dd' % self.num_joints, *self.cmd_joint_positions[i0][:self.num_joints]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_pos_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_pos_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joint_pos_cmd_t()
        self.utime, self.num_joints, self.num_confs = struct.unpack(">qii", buf.read(16))
        self.wait_for_ack = bool(struct.unpack('b', buf.read(1))[0])
        self.cmd_joint_positions = []
        for i0 in range(self.num_confs):
            self.cmd_joint_positions.append(struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joint_pos_cmd_t in parents: return 0
        tmphash = (0x10eeaf10c84dc97f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joint_pos_cmd_t._packed_fingerprint is None:
            joint_pos_cmd_t._packed_fingerprint = struct.pack(">Q", joint_pos_cmd_t._get_hash_recursive([]))
        return joint_pos_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

