"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pause_cmd(object):
    __slots__ = ["utime", "data", "source"]

    __typenames__ = ["int64_t", "boolean", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.utime = 0
        self.data = False
        self.source = ""

    def encode(self):
        buf = BytesIO()
        buf.write(pause_cmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.data))
        __source_encoded = self.source.encode('utf-8')
        buf.write(struct.pack('>I', len(__source_encoded)+1))
        buf.write(__source_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pause_cmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pause_cmd._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pause_cmd()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.data = bool(struct.unpack('b', buf.read(1))[0])
        __source_len = struct.unpack('>I', buf.read(4))[0]
        self.source = buf.read(__source_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pause_cmd in parents: return 0
        tmphash = (0x1a28f43141e42fe) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pause_cmd._packed_fingerprint is None:
            pause_cmd._packed_fingerprint = struct.pack(">Q", pause_cmd._get_hash_recursive([]))
        return pause_cmd._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

