"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import robot_msgs.pose_t

class pose_timestamped_t(object):
    __slots__ = ["utime", "pose"]

    __typenames__ = ["int64_t", "robot_msgs.pose_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.utime = 0
        self.pose = robot_msgs.pose_t()

    def encode(self):
        buf = BytesIO()
        buf.write(pose_timestamped_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.pose._get_packed_fingerprint() == robot_msgs.pose_t._get_packed_fingerprint()
        self.pose._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pose_timestamped_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pose_timestamped_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pose_timestamped_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.pose = robot_msgs.pose_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if pose_timestamped_t in parents: return 0
        newparents = parents + [pose_timestamped_t]
        tmphash = (0x276852632db173fa+ robot_msgs.pose_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pose_timestamped_t._packed_fingerprint is None:
            pose_timestamped_t._packed_fingerprint = struct.pack(">Q", pose_timestamped_t._get_hash_recursive([]))
        return pose_timestamped_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", pose_timestamped_t._get_packed_fingerprint())[0]

