"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import drake.lcmt_point

import drake.lcmt_quaternion

class pose_t(object):
    __slots__ = ["translation", "rotation"]

    __typenames__ = ["drake.lcmt_point", "drake.lcmt_quaternion"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.translation = drake.lcmt_point()
        self.rotation = drake.lcmt_quaternion()

    def encode(self):
        buf = BytesIO()
        buf.write(pose_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.translation._get_packed_fingerprint() == drake.lcmt_point._get_packed_fingerprint()
        self.translation._encode_one(buf)
        assert self.rotation._get_packed_fingerprint() == drake.lcmt_quaternion._get_packed_fingerprint()
        self.rotation._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pose_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pose_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pose_t()
        self.translation = drake.lcmt_point._decode_one(buf)
        self.rotation = drake.lcmt_quaternion._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if pose_t in parents: return 0
        newparents = parents + [pose_t]
        tmphash = (0x1275bd1ccbdaf47f+ drake.lcmt_point._get_hash_recursive(newparents)+ drake.lcmt_quaternion._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pose_t._packed_fingerprint is None:
            pose_t._packed_fingerprint = struct.pack(">Q", pose_t._get_hash_recursive([]))
        return pose_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", pose_t._get_packed_fingerprint())[0]

