"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import drake.lcmt_force_torque

import robot_msgs.pose_t

import robot_msgs.twist_t

class robot_state_t(object):
    __slots__ = ["utime", "num_joints", "joint_name", "joint_position", "joint_velocity", "joint_effort", "pose", "twist", "force_torque"]

    __typenames__ = ["int64_t", "int16_t", "string", "float", "float", "float", "robot_msgs.pose_t", "robot_msgs.twist_t", "drake.lcmt_force_torque"]

    __dimensions__ = [None, None, ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], None, None, None]

    def __init__(self):
        self.utime = 0
        self.num_joints = 0
        self.joint_name = []
        self.joint_position = []
        self.joint_velocity = []
        self.joint_effort = []
        self.pose = robot_msgs.pose_t()
        self.twist = robot_msgs.twist_t()
        self.force_torque = drake.lcmt_force_torque()

    def encode(self):
        buf = BytesIO()
        buf.write(robot_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.utime, self.num_joints))
        for i0 in range(self.num_joints):
            __joint_name_encoded = self.joint_name[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__joint_name_encoded)+1))
            buf.write(__joint_name_encoded)
            buf.write(b"\0")
        buf.write(struct.pack('>%df' % self.num_joints, *self.joint_position[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.joint_velocity[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.joint_effort[:self.num_joints]))
        assert self.pose._get_packed_fingerprint() == robot_msgs.pose_t._get_packed_fingerprint()
        self.pose._encode_one(buf)
        assert self.twist._get_packed_fingerprint() == robot_msgs.twist_t._get_packed_fingerprint()
        self.twist._encode_one(buf)
        assert self.force_torque._get_packed_fingerprint() == drake.lcmt_force_torque._get_packed_fingerprint()
        self.force_torque._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_state_t()
        self.utime, self.num_joints = struct.unpack(">qh", buf.read(10))
        self.joint_name = []
        for i0 in range(self.num_joints):
            __joint_name_len = struct.unpack('>I', buf.read(4))[0]
            self.joint_name.append(buf.read(__joint_name_len)[:-1].decode('utf-8', 'replace'))
        self.joint_position = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.joint_velocity = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.joint_effort = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.pose = robot_msgs.pose_t._decode_one(buf)
        self.twist = robot_msgs.twist_t._decode_one(buf)
        self.force_torque = drake.lcmt_force_torque._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_state_t in parents: return 0
        newparents = parents + [robot_state_t]
        tmphash = (0x10a7718a75ccc314+ robot_msgs.pose_t._get_hash_recursive(newparents)+ robot_msgs.twist_t._get_hash_recursive(newparents)+ drake.lcmt_force_torque._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_state_t._packed_fingerprint is None:
            robot_state_t._packed_fingerprint = struct.pack(">Q", robot_state_t._get_hash_recursive([]))
        return robot_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_state_t._get_packed_fingerprint())[0]

