"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_modes_t(object):
    __slots__ = []

    __typenames__ = []

    __dimensions__ = []

    kOther = 0
    kIdle = 1
    kMove = 2
    kGuiding = 3
    kReflex = 4
    kUserStopped = 5
    kAutomaticErrorRecovery = 6

    def __init__(self):
        pass

    def encode(self):
        buf = BytesIO()
        buf.write(robot_modes_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        pass

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_modes_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_modes_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_modes_t()
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_modes_t in parents: return 0
        tmphash = (0x12345678) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_modes_t._packed_fingerprint is None:
            robot_modes_t._packed_fingerprint = struct.pack(">Q", robot_modes_t._get_hash_recursive([]))
        return robot_modes_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_modes_t._get_packed_fingerprint())[0]

