"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_joint(object):
    __slots__ = ["joint_name", "position_lower_limit", "position_upper_limit", "velocity_lower_limit", "velocity_upper_limit", "acceleration_lower_limit", "acceleration_upper_limit"]

    __typenames__ = ["string", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.joint_name = ""
        self.position_lower_limit = 0.0
        self.position_upper_limit = 0.0
        self.velocity_lower_limit = 0.0
        self.velocity_upper_limit = 0.0
        self.acceleration_lower_limit = 0.0
        self.acceleration_upper_limit = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(robot_joint._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __joint_name_encoded = self.joint_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__joint_name_encoded)+1))
        buf.write(__joint_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">dddddd", self.position_lower_limit, self.position_upper_limit, self.velocity_lower_limit, self.velocity_upper_limit, self.acceleration_lower_limit, self.acceleration_upper_limit))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_joint._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_joint._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_joint()
        __joint_name_len = struct.unpack('>I', buf.read(4))[0]
        self.joint_name = buf.read(__joint_name_len)[:-1].decode('utf-8', 'replace')
        self.position_lower_limit, self.position_upper_limit, self.velocity_lower_limit, self.velocity_upper_limit, self.acceleration_lower_limit, self.acceleration_upper_limit = struct.unpack(">dddddd", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_joint in parents: return 0
        tmphash = (0x2c80d2639f6fc3cf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_joint._packed_fingerprint is None:
            robot_joint._packed_fingerprint = struct.pack(">Q", robot_joint._get_hash_recursive([]))
        return robot_joint._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_joint._get_packed_fingerprint())[0]

